import 'plant_cache_service.dart';

/// Offline Agricultural Encyclopedia.
/// Pre-seeds PlantCacheService with static data for 22 common Turkish crops.
/// Works without internet — fulfills the "Offline Agricultural Encyclopedia"
/// requirement in the proposal (Section 6.1.1).
class OfflineEncyclopedia {
  // ── Static encyclopedia keyed by Turkish common name ──────────────────────
  static const Map<String, Map<String, dynamic>> _crops = {
    'domates': {
      'other_names': 'Domates, Tomato',
      'type': 'vegetable',
      'cycle': 'Annual',
      'watering': 'Average',
      'sunlight': 'Full Sun',
      'soil': 'Loamy, Well-drained',
      'growth_rate': 'Moderate',
      'care_level': 'Medium',
      'maintenance': 'Medium',
      'drought_tolerant': false,
      'salt_tolerant': false,
      'tropical': false,
      'invasive': false,
      'medicinal': false,
      'poisonous_to_humans': false,
      'poisonous_to_pets': false,
      'edible_fruit': true,
      'edible_leaf': false,
      'flowering_season': 'Yaz',
      'fruiting_season': 'Yaz-Sonbahar',
      'harvest_season': 'Temmuz-Ekim',
      'harvest_method': 'Elle hasat, daldan koparılarak',
      'pruning_month': 'Mayıs, Haziran',
      'origin': 'Güney Amerika',
      'propagation': 'Tohumla, Fideyle',
      'pest_susceptibility': 'Beyazsinek, Kırmızı örümcek, Botrytis, Alternaria yaprak lekesi',
      'ideal_temp_min': 18.0,
      'ideal_temp_max': 27.0,
      'ideal_ph_min': 6.0,
      'ideal_ph_max': 6.8,
      'water_need_mm_week': 25.0,
      'harvest_days': 75,
      'seeds_per_dekar': 350,
      'row_spacing_cm': 70,
      'plant_spacing_cm': 50,
      'depth_cm': 1,
      'care_description':
          '💧 Sulama: Haftada 2-3 kez derin sulama. Toprağın üst 5cm\'i kuruyunca sulayın.\n\n'
          '☀️ Güneş İhtiyacı: Günlük en az 8 saat doğrudan güneş.\n\n'
          '✂️ Budama: Sürgün alma (kalem alma) her hafta yapılmalı.\n\n'
          '🧪 Gübreleme: Dikimde 15-15-15 NPK; çiçek döneminde potasyum ağırlıklı.',
    },
    'biber': {
      'other_names': 'Biber, Pepper',
      'type': 'vegetable',
      'cycle': 'Annual',
      'watering': 'Average',
      'sunlight': 'Full Sun',
      'soil': 'Loamy, Sandy loam',
      'growth_rate': 'Moderate',
      'care_level': 'Medium',
      'maintenance': 'Medium',
      'drought_tolerant': false,
      'edible_fruit': true,
      'edible_leaf': false,
      'flowering_season': 'Yaz',
      'fruiting_season': 'Yaz',
      'harvest_season': 'Temmuz-Ekim',
      'harvest_method': 'Elle hasat',
      'origin': 'Orta Amerika',
      'propagation': 'Tohumla, Fideyle',
      'pest_susceptibility': 'Trips, Beyazsinek, Verticillium solgunluğu',
      'ideal_temp_min': 20.0,
      'ideal_temp_max': 30.0,
      'ideal_ph_min': 6.0,
      'ideal_ph_max': 7.0,
      'water_need_mm_week': 20.0,
      'harvest_days': 80,
      'seeds_per_dekar': 400,
      'row_spacing_cm': 60,
      'plant_spacing_cm': 40,
      'depth_cm': 1,
      'care_description':
          '💧 Sulama: Düzenli sulama, aşırı nemden kaçının.\n\n'
          '☀️ Güneş İhtiyacı: Tam güneş, 8+ saat.\n\n'
          '✂️ Budama: İlk çiçekler atılarak güçlü büyüme sağlanır.\n\n'
          '🧪 Gübreleme: Azot ağırlıklı başlangıç; meyve dönemi fosfor-potasyum.',
    },
    'patlıcan': {
      'other_names': 'Patlıcan, Eggplant',
      'type': 'vegetable',
      'cycle': 'Annual',
      'watering': 'Average',
      'sunlight': 'Full Sun',
      'soil': 'Well-drained, Loamy',
      'growth_rate': 'Moderate',
      'care_level': 'Medium',
      'maintenance': 'Medium',
      'drought_tolerant': false,
      'edible_fruit': true,
      'edible_leaf': false,
      'harvest_season': 'Ağustos-Ekim',
      'harvest_method': 'Elle hasat, kesilerek',
      'origin': 'Güney Asya',
      'propagation': 'Tohumla, Fideyle',
      'pest_susceptibility': 'Colorado böceği, Kırmızı örümcek, Fusarium',
      'ideal_temp_min': 22.0,
      'ideal_temp_max': 32.0,
      'ideal_ph_min': 5.5,
      'ideal_ph_max': 6.5,
      'water_need_mm_week': 22.0,
      'harvest_days': 85,
      'row_spacing_cm': 70,
      'plant_spacing_cm': 50,
      'depth_cm': 1,
      'care_description':
          '💧 Sulama: Haftalık 2 kez, kök bölgesine.\n\n'
          '☀️ Güneş İhtiyacı: 8-10 saat tam güneş.\n\n'
          '✂️ Budama: 3-4 ana dal bırakılır, diğerleri çıkarılır.\n\n'
          '🧪 Gübreleme: Ekim öncesi çiftlik gübresi; büyüme döneminde azot.',
    },
    'salatalık': {
      'other_names': 'Salatalık, Cucumber',
      'type': 'vegetable',
      'cycle': 'Annual',
      'watering': 'Frequent',
      'sunlight': 'Full Sun',
      'soil': 'Loamy, Well-drained',
      'growth_rate': 'Fast',
      'care_level': 'Low',
      'maintenance': 'Low',
      'drought_tolerant': false,
      'edible_fruit': true,
      'edible_leaf': false,
      'harvest_season': 'Haziran-Eylül',
      'harvest_method': 'Elle hasat, sık aralıklarla',
      'origin': 'Güney Asya',
      'propagation': 'Tohumla',
      'pest_susceptibility': 'Külleme, Mildiyö, Kırmızı örümcek',
      'ideal_temp_min': 18.0,
      'ideal_temp_max': 30.0,
      'ideal_ph_min': 6.0,
      'ideal_ph_max': 7.0,
      'water_need_mm_week': 30.0,
      'harvest_days': 55,
      'row_spacing_cm': 100,
      'plant_spacing_cm': 30,
      'depth_cm': 2,
      'care_description':
          '💧 Sulama: Günlük sulama gerektirebilir, toprak her zaman nemli kalmalı.\n\n'
          '☀️ Güneş İhtiyacı: Tam güneş.\n\n'
          '✂️ Budama: Tırmanma kafesine yönlendirme.\n\n'
          '🧪 Gübreleme: Potasyum ağırlıklı — kalite ve tat için.',
    },
    'buğday': {
      'other_names': 'Buğday, Wheat',
      'type': 'grain',
      'cycle': 'Annual',
      'watering': 'Minimum',
      'sunlight': 'Full Sun',
      'soil': 'Clay, Loamy',
      'growth_rate': 'Moderate',
      'care_level': 'Low',
      'maintenance': 'Low',
      'drought_tolerant': true,
      'edible_fruit': true,
      'edible_leaf': false,
      'harvest_season': 'Haziran-Temmuz',
      'harvest_method': 'Biçerdöver',
      'origin': 'Orta Doğu',
      'propagation': 'Tohumla',
      'pest_susceptibility': 'Süne, Septorya, Sarı pas, Kara pas',
      'ideal_temp_min': 10.0,
      'ideal_temp_max': 24.0,
      'ideal_ph_min': 6.0,
      'ideal_ph_max': 7.5,
      'water_need_mm_week': 10.0,
      'harvest_days': 210,
      'seeds_per_dekar': 20000,
      'row_spacing_cm': 20,
      'plant_spacing_cm': 5,
      'depth_cm': 4,
      'care_description':
          '💧 Sulama: Kışlık buğday yağışa bağımlı; kritik dönemler: kardeşlenme ve başaklanma.\n\n'
          '☀️ Güneş İhtiyacı: Tam güneş.\n\n'
          '✂️ Budama: Uygulanmaz.\n\n'
          '🧪 Gübreleme: Ekim: DAP; kardeşlenme: Amonyum Nitrat; sapa kalkma: Üre.',
    },
    'mısır': {
      'other_names': 'Mısır, Corn, Maize',
      'type': 'grain',
      'cycle': 'Annual',
      'watering': 'Average',
      'sunlight': 'Full Sun',
      'soil': 'Loamy, Sandy loam',
      'growth_rate': 'Fast',
      'care_level': 'Low',
      'maintenance': 'Low',
      'drought_tolerant': false,
      'edible_fruit': true,
      'edible_leaf': false,
      'harvest_season': 'Eylül-Ekim',
      'harvest_method': 'Elle veya makine',
      'origin': 'Orta Amerika',
      'propagation': 'Tohumla',
      'pest_susceptibility': 'Mısır kurtları, Yaprak yanıklığı, Smut',
      'ideal_temp_min': 18.0,
      'ideal_temp_max': 32.0,
      'ideal_ph_min': 5.8,
      'ideal_ph_max': 7.0,
      'water_need_mm_week': 20.0,
      'harvest_days': 120,
      'seeds_per_dekar': 700,
      'row_spacing_cm': 70,
      'plant_spacing_cm': 20,
      'depth_cm': 5,
      'care_description':
          '💧 Sulama: Tepe sürmesi ve koçan bağlama dönemlerinde kritik.\n\n'
          '☀️ Güneş İhtiyacı: Tam güneş, uzun gün bitkisi.\n\n'
          '✂️ Budama: Yan koçanlar çıkarılabilir.\n\n'
          '🧪 Gübreleme: Yüksek azot ihtiyacı; bölünmüş uygulama en verimli.',
    },
    'patates': {
      'other_names': 'Patates, Potato',
      'type': 'vegetable',
      'cycle': 'Annual',
      'watering': 'Average',
      'sunlight': 'Full Sun',
      'soil': 'Sandy loam, Well-drained',
      'growth_rate': 'Moderate',
      'care_level': 'Medium',
      'maintenance': 'Medium',
      'drought_tolerant': false,
      'edible_fruit': true,
      'edible_leaf': false,
      'harvest_season': 'Temmuz-Eylül',
      'harvest_method': 'Patates kazma makinesi veya elle',
      'origin': 'Güney Amerika',
      'propagation': 'Tohumluk yumrularla',
      'pest_susceptibility': 'Colorado böceği, Mildiyö, Scab, Rhizoctonia',
      'ideal_temp_min': 15.0,
      'ideal_temp_max': 22.0,
      'ideal_ph_min': 5.0,
      'ideal_ph_max': 6.5,
      'water_need_mm_week': 20.0,
      'harvest_days': 90,
      'seeds_per_dekar': 350,
      'row_spacing_cm': 70,
      'plant_spacing_cm': 30,
      'depth_cm': 10,
      'care_description':
          '💧 Sulama: Düzenli, toprağı hafif nemli tutun; hasat öncesi 2 haftada kesin.\n\n'
          '☀️ Güneş İhtiyacı: Tam güneş.\n\n'
          '✂️ Budama: Uygulanmaz.\n\n'
          '🧪 Gübreleme: Potasyum ve fosfor ağırlıklı; fazla azottan kaçının.',
    },
    'soğan': {
      'other_names': 'Soğan, Onion',
      'type': 'vegetable',
      'cycle': 'Biennial',
      'watering': 'Average',
      'sunlight': 'Full Sun',
      'soil': 'Well-drained, Sandy loam',
      'growth_rate': 'Slow',
      'care_level': 'Low',
      'maintenance': 'Low',
      'drought_tolerant': true,
      'edible_fruit': true,
      'edible_leaf': true,
      'harvest_season': 'Temmuz-Ağustos',
      'harvest_method': 'Elle sökülerek',
      'origin': 'Orta Asya',
      'propagation': 'Tohumla, Set\'le',
      'pest_susceptibility': 'Soğan sineği, Botrytis, Fusarium',
      'ideal_temp_min': 13.0,
      'ideal_temp_max': 24.0,
      'ideal_ph_min': 6.0,
      'ideal_ph_max': 7.0,
      'water_need_mm_week': 15.0,
      'harvest_days': 120,
      'seeds_per_dekar': 800,
      'row_spacing_cm': 30,
      'plant_spacing_cm': 10,
      'depth_cm': 2,
      'care_description':
          '💧 Sulama: Orta düzey; hasat öncesi son 2 hafta sulama yapılmaz.\n\n'
          '☀️ Güneş İhtiyacı: Tam güneş, uzun gün çeşitleri Türkiye\'de yaygın.\n\n'
          '✂️ Budama: Uygulanmaz.\n\n'
          '🧪 Gübreleme: Azot başlangıçta, potasyum olgunlaşmada.',
    },
    'sarımsak': {
      'other_names': 'Sarımsak, Garlic',
      'type': 'vegetable',
      'cycle': 'Annual',
      'watering': 'Minimum',
      'sunlight': 'Full Sun',
      'soil': 'Well-drained, Loamy',
      'growth_rate': 'Slow',
      'care_level': 'Low',
      'maintenance': 'Low',
      'drought_tolerant': true,
      'medicinal': true,
      'edible_fruit': true,
      'edible_leaf': true,
      'harvest_season': 'Haziran-Temmuz',
      'harvest_method': 'Elle sökülerek, kurutularak',
      'origin': 'Orta Asya',
      'propagation': 'Diş ile',
      'pest_susceptibility': 'Botrytis, Beyaz çürüklük, Soğan sineği',
      'ideal_temp_min': 0.0,
      'ideal_temp_max': 20.0,
      'ideal_ph_min': 6.0,
      'ideal_ph_max': 7.5,
      'water_need_mm_week': 8.0,
      'harvest_days': 240,
      'seeds_per_dekar': 1200,
      'row_spacing_cm': 25,
      'plant_spacing_cm': 10,
      'depth_cm': 5,
      'care_description':
          '💧 Sulama: Az sulama; çürüme riskine karşı dikkatli olun.\n\n'
          '☀️ Güneş İhtiyacı: Tam güneş.\n\n'
          '✂️ Budama: Scape\'ler (çiçek sapları) kesilirse baş daha iri olur.\n\n'
          '🧪 Gübreleme: Sonbahar ekiminde fosfor; ilkbaharda hafif azot.',
    },
    'havuç': {
      'other_names': 'Havuç, Carrot',
      'type': 'vegetable',
      'cycle': 'Biennial',
      'watering': 'Average',
      'sunlight': 'Full Sun',
      'soil': 'Sandy, Deep, Well-drained',
      'growth_rate': 'Moderate',
      'care_level': 'Low',
      'maintenance': 'Low',
      'drought_tolerant': false,
      'edible_fruit': true,
      'edible_leaf': false,
      'harvest_season': 'Temmuz-Kasım',
      'harvest_method': 'Elle sökülerek',
      'origin': 'Afganistan',
      'propagation': 'Tohumla',
      'pest_susceptibility': 'Havuç sineği, Alternaria yaprak yanıklığı',
      'ideal_temp_min': 10.0,
      'ideal_temp_max': 20.0,
      'ideal_ph_min': 6.0,
      'ideal_ph_max': 6.8,
      'water_need_mm_week': 15.0,
      'harvest_days': 80,
      'row_spacing_cm': 30,
      'plant_spacing_cm': 5,
      'depth_cm': 1,
      'care_description':
          '💧 Sulama: Düzenli; kuraklık havucun çatlamasına neden olur.\n\n'
          '☀️ Güneş İhtiyacı: Tam güneş.\n\n'
          '✂️ Budama: Seyreltime yapılır (her 5cm\'de 1 bitki).\n\n'
          '🧪 Gübreleme: Fosfor ve potasyum; azottan kaçının (saplar büyür, kök küçük kalır).',
    },
    'fasulye': {
      'other_names': 'Fasulye, Bean',
      'type': 'vegetable',
      'cycle': 'Annual',
      'watering': 'Average',
      'sunlight': 'Full Sun',
      'soil': 'Loamy, Well-drained',
      'growth_rate': 'Fast',
      'care_level': 'Low',
      'maintenance': 'Low',
      'drought_tolerant': false,
      'edible_fruit': true,
      'edible_leaf': false,
      'harvest_season': 'Temmuz-Eylül',
      'harvest_method': 'Elle hasat',
      'origin': 'Orta Amerika',
      'propagation': 'Tohumla',
      'pest_susceptibility': 'Fasulye tahtakurusu, Mosaik virüsü, Antraknoz',
      'ideal_temp_min': 16.0,
      'ideal_temp_max': 28.0,
      'ideal_ph_min': 6.0,
      'ideal_ph_max': 7.0,
      'water_need_mm_week': 18.0,
      'harvest_days': 65,
      'seeds_per_dekar': 1500,
      'row_spacing_cm': 50,
      'plant_spacing_cm': 10,
      'depth_cm': 3,
      'care_description':
          '💧 Sulama: Çiçeklenme döneminde düzenli sulama kritik.\n\n'
          '☀️ Güneş İhtiyacı: Tam güneş.\n\n'
          '✂️ Budama: Uygulanmaz.\n\n'
          '🧪 Gübreleme: Az azot (kendi azotunu bağlar); fosfor ve potasyum yeterli.',
    },
    'kabak': {
      'other_names': 'Kabak, Zucchini, Squash',
      'type': 'vegetable',
      'cycle': 'Annual',
      'watering': 'Frequent',
      'sunlight': 'Full Sun',
      'soil': 'Rich, Well-drained',
      'growth_rate': 'Fast',
      'care_level': 'Low',
      'maintenance': 'Low',
      'drought_tolerant': false,
      'edible_fruit': true,
      'edible_leaf': false,
      'harvest_season': 'Haziran-Eylül',
      'harvest_method': 'Elle hasat, erken hasat kaliteyi artırır',
      'origin': 'Amerika',
      'propagation': 'Tohumla',
      'pest_susceptibility': 'Külleme, Kabak sineği, Mildiyö',
      'ideal_temp_min': 18.0,
      'ideal_temp_max': 30.0,
      'ideal_ph_min': 6.0,
      'ideal_ph_max': 7.5,
      'water_need_mm_week': 28.0,
      'harvest_days': 55,
      'seeds_per_dekar': 500,
      'row_spacing_cm': 120,
      'plant_spacing_cm': 60,
      'depth_cm': 3,
      'care_description':
          '💧 Sulama: Bol sulama; yaprakları ıslatmaktan kaçının (külleme riski).\n\n'
          '☀️ Güneş İhtiyacı: Tam güneş.\n\n'
          '✂️ Budama: Kalabalık yapraklar hava sirkülasyonu için temizlenir.\n\n'
          '🧪 Gübreleme: Dengeli NPK; çiçeklenme öncesi potasyum artışı.',
    },
    'çilek': {
      'other_names': 'Çilek, Strawberry',
      'type': 'fruit',
      'cycle': 'Perennial',
      'watering': 'Average',
      'sunlight': 'Full Sun',
      'soil': 'Sandy loam, Well-drained',
      'growth_rate': 'Moderate',
      'care_level': 'Medium',
      'maintenance': 'Medium',
      'drought_tolerant': false,
      'edible_fruit': true,
      'edible_leaf': false,
      'flowering_season': 'İlkbahar',
      'fruiting_season': 'İlkbahar-Yaz',
      'harvest_season': 'Nisan-Haziran',
      'harvest_method': 'Elle hasat, nazikçe toplanarak',
      'origin': 'Avrupa, Amerika',
      'propagation': 'Stolonlarla (yavru bitki)',
      'pest_susceptibility': 'Kırmızı örümcek, Botrytis çürüklüğü, Kökene köy',
      'ideal_temp_min': 10.0,
      'ideal_temp_max': 22.0,
      'ideal_ph_min': 5.5,
      'ideal_ph_max': 6.5,
      'water_need_mm_week': 20.0,
      'harvest_days': 90,
      'seeds_per_dekar': 3000,
      'row_spacing_cm': 40,
      'plant_spacing_cm': 25,
      'depth_cm': 1,
      'care_description':
          '💧 Sulama: Damla sulama ideal; meyveye su değmemeli.\n\n'
          '☀️ Güneş İhtiyacı: Tam güneş, 6-8 saat.\n\n'
          '✂️ Budama: Hasat sonrası eski yapraklar temizlenir.\n\n'
          '🧪 Gübreleme: Çiçeklenme öncesi potasyum-fosfor; azottan kaçının.',
    },
    'karpuz': {
      'other_names': 'Karpuz, Watermelon',
      'type': 'fruit',
      'cycle': 'Annual',
      'watering': 'Average',
      'sunlight': 'Full Sun',
      'soil': 'Sandy loam',
      'growth_rate': 'Fast',
      'care_level': 'Medium',
      'maintenance': 'Medium',
      'drought_tolerant': false,
      'tropical': true,
      'edible_fruit': true,
      'harvest_season': 'Temmuz-Eylül',
      'harvest_method': 'Saptan keserek',
      'origin': 'Afrika',
      'propagation': 'Tohumla, Fideyle',
      'pest_susceptibility': 'Antepfıstığı sineği, Mildiyö, Solgunluk',
      'ideal_temp_min': 22.0,
      'ideal_temp_max': 35.0,
      'ideal_ph_min': 6.0,
      'ideal_ph_max': 7.0,
      'water_need_mm_week': 22.0,
      'harvest_days': 85,
      'seeds_per_dekar': 400,
      'row_spacing_cm': 200,
      'plant_spacing_cm': 100,
      'depth_cm': 2,
      'care_description':
          '💧 Sulama: Meyve oluşumuna kadar bol; olgunlaşma döneminde azalt.\n\n'
          '☀️ Güneş İhtiyacı: Bol güneş, sıcak iklim şart.\n\n'
          '✂️ Budama: Ana sap + 2 yan sap bırakılır.\n\n'
          '🧪 Gübreleme: Çiçeklenme öncesi azot; meyve bağlama döneminde potasyum.',
    },
    'kavun': {
      'other_names': 'Kavun, Melon',
      'type': 'fruit',
      'cycle': 'Annual',
      'watering': 'Average',
      'sunlight': 'Full Sun',
      'soil': 'Sandy loam, Well-drained',
      'growth_rate': 'Fast',
      'care_level': 'Medium',
      'maintenance': 'Medium',
      'drought_tolerant': false,
      'edible_fruit': true,
      'harvest_season': 'Temmuz-Ağustos',
      'harvest_method': 'Saptan keserek',
      'origin': 'Orta Asya',
      'propagation': 'Tohumla, Fideyle',
      'pest_susceptibility': 'Mildiyö, Külleme, Kavun sineği',
      'ideal_temp_min': 22.0,
      'ideal_temp_max': 35.0,
      'ideal_ph_min': 6.0,
      'ideal_ph_max': 7.0,
      'water_need_mm_week': 20.0,
      'harvest_days': 80,
      'seeds_per_dekar': 500,
      'row_spacing_cm': 180,
      'plant_spacing_cm': 80,
      'depth_cm': 2,
      'care_description':
          '💧 Sulama: Düzenli; olgunlaşmada azalt (şeker oranı artar).\n\n'
          '☀️ Güneş İhtiyacı: Tam güneş.\n\n'
          '✂️ Budama: Her dalda 1-2 meyve bırak.\n\n'
          '🧪 Gübreleme: Potasyum ağırlıklı olgunlaşma dönemi gübresi.',
    },
    'ispanak': {
      'other_names': 'Ispanak, Spinach',
      'type': 'vegetable',
      'cycle': 'Annual',
      'watering': 'Average',
      'sunlight': 'Partial Shade',
      'soil': 'Rich, Well-drained',
      'growth_rate': 'Fast',
      'care_level': 'Low',
      'maintenance': 'Low',
      'drought_tolerant': false,
      'edible_leaf': true,
      'edible_fruit': false,
      'harvest_season': 'Ekim-Kasım, Mart-Nisan',
      'harvest_method': 'Dış yapraklar elle koparılarak',
      'origin': 'Orta Asya',
      'propagation': 'Tohumla',
      'pest_susceptibility': 'Mildiyö, Yaprak maden sineği',
      'ideal_temp_min': 5.0,
      'ideal_temp_max': 18.0,
      'ideal_ph_min': 6.5,
      'ideal_ph_max': 7.5,
      'water_need_mm_week': 15.0,
      'harvest_days': 45,
      'row_spacing_cm': 30,
      'plant_spacing_cm': 8,
      'depth_cm': 2,
      'care_description':
          '💧 Sulama: Düzenli nemli tutun; kuruluğa hassas.\n\n'
          '☀️ Güneş İhtiyacı: Kısmi gölge tolere eder; sıcakta hızla tohumlanır.\n\n'
          '✂️ Budama: Dış yaprak hasadı iç yaprakların büyümesini teşvik eder.\n\n'
          '🧪 Gübreleme: Azot ağırlıklı; gövde ve yaprak gelişimi için.',
    },
    'marul': {
      'other_names': 'Marul, Lettuce',
      'type': 'vegetable',
      'cycle': 'Annual',
      'watering': 'Average',
      'sunlight': 'Partial Shade',
      'soil': 'Rich, Moist',
      'growth_rate': 'Fast',
      'care_level': 'Low',
      'maintenance': 'Low',
      'drought_tolerant': false,
      'edible_leaf': true,
      'edible_fruit': false,
      'harvest_season': 'İlkbahar-Sonbahar',
      'harvest_method': 'Elle, kökten kesilerek',
      'origin': 'Akdeniz',
      'propagation': 'Tohumla',
      'pest_susceptibility': 'Yaprak bitleri, Salyangoz, Botrytis',
      'ideal_temp_min': 7.0,
      'ideal_temp_max': 20.0,
      'ideal_ph_min': 6.0,
      'ideal_ph_max': 7.0,
      'water_need_mm_week': 18.0,
      'harvest_days': 50,
      'row_spacing_cm': 30,
      'plant_spacing_cm': 25,
      'depth_cm': 1,
      'care_description':
          '💧 Sulama: Sık ama hafif sulama; kök çürüklüğünden kaçının.\n\n'
          '☀️ Güneş İhtiyacı: Serin hava sever; yazın gölge faydalı.\n\n'
          '✂️ Budama: Dış yaprakların hasat edilmesi büyümeyi destekler.\n\n'
          '🧪 Gübreleme: Hafif azot; organik gübre tercih edilir.',
    },
    'ayçiçeği': {
      'other_names': 'Ayçiçeği, Sunflower',
      'type': 'grain',
      'cycle': 'Annual',
      'watering': 'Average',
      'sunlight': 'Full Sun',
      'soil': 'Well-drained, Loamy',
      'growth_rate': 'Fast',
      'care_level': 'Low',
      'maintenance': 'Low',
      'drought_tolerant': true,
      'edible_fruit': true,
      'edible_leaf': false,
      'flowering_season': 'Yaz',
      'harvest_season': 'Eylül-Ekim',
      'harvest_method': 'Biçerdöver',
      'origin': 'Kuzey Amerika',
      'propagation': 'Tohumla',
      'pest_susceptibility': 'Broomrape (canavarotu), Sklerotinia, Pas hastalığı',
      'ideal_temp_min': 18.0,
      'ideal_temp_max': 30.0,
      'ideal_ph_min': 6.0,
      'ideal_ph_max': 7.5,
      'water_need_mm_week': 15.0,
      'harvest_days': 120,
      'seeds_per_dekar': 5000,
      'row_spacing_cm': 70,
      'plant_spacing_cm': 30,
      'depth_cm': 5,
      'care_description':
          '💧 Sulama: Çiçeklenme başlangıcında kritik; kuraklığa dayanıklı.\n\n'
          '☀️ Güneş İhtiyacı: Tam güneş, günlük en az 8 saat.\n\n'
          '✂️ Budama: Uygulanmaz.\n\n'
          '🧪 Gübreleme: Fosfor ve potasyum; aşırı azot yatmaya neden olur.',
    },
    'elma': {
      'other_names': 'Elma, Apple',
      'type': 'fruit',
      'cycle': 'Perennial',
      'watering': 'Average',
      'sunlight': 'Full Sun',
      'soil': 'Well-drained, Loamy',
      'growth_rate': 'Slow',
      'care_level': 'High',
      'maintenance': 'High',
      'drought_tolerant': false,
      'edible_fruit': true,
      'edible_leaf': false,
      'flowering_season': 'Nisan',
      'fruiting_season': 'Yaz-Sonbahar',
      'harvest_season': 'Ağustos-Kasım',
      'harvest_method': 'Elle hasat',
      'pruning_month': 'Şubat, Mart',
      'origin': 'Orta Asya',
      'propagation': 'Aşılama',
      'pest_susceptibility': 'Elma içkurdu, Ateş yanıklığı, Elma uyuzu (karaleke)',
      'ideal_temp_min': 5.0,
      'ideal_temp_max': 24.0,
      'ideal_ph_min': 6.0,
      'ideal_ph_max': 7.0,
      'water_need_mm_week': 20.0,
      'harvest_days': 150,
      'care_description':
          '💧 Sulama: Vejetasyon döneminde düzenli; kuraklıkta meyve dökülür.\n\n'
          '☀️ Güneş İhtiyacı: Tam güneş, iç kısımlara ışık girmeli.\n\n'
          '✂️ Budama: Kış budaması zorunlu; kuru, hasta, çapraz dallar kesilir.\n\n'
          '🧪 Gübreleme: Şubat\'ta dengeli NPK; meyve büyüme döneminde potasyum.',
    },
    'üzüm': {
      'other_names': 'Üzüm, Grape',
      'type': 'fruit',
      'cycle': 'Perennial',
      'watering': 'Minimum',
      'sunlight': 'Full Sun',
      'soil': 'Well-drained, Sandy loam',
      'growth_rate': 'Moderate',
      'care_level': 'High',
      'maintenance': 'High',
      'drought_tolerant': true,
      'edible_fruit': true,
      'edible_leaf': true,
      'flowering_season': 'Mayıs-Haziran',
      'fruiting_season': 'Yaz-Sonbahar',
      'harvest_season': 'Ağustos-Ekim',
      'harvest_method': 'Makasla salkım kesilerek',
      'pruning_month': 'Şubat',
      'origin': 'Kafkasya',
      'propagation': 'Çelikleme',
      'pest_susceptibility': 'Oidium (külleme), Mildiyö, Phylloxera',
      'ideal_temp_min': 10.0,
      'ideal_temp_max': 35.0,
      'ideal_ph_min': 5.5,
      'ideal_ph_max': 7.0,
      'water_need_mm_week': 8.0,
      'harvest_days': 150,
      'care_description':
          '💧 Sulama: Kök yerleştikten sonra az sulama; fazla su kaliteyi düşürür.\n\n'
          '☀️ Güneş İhtiyacı: Tam güneş şart; şeker oranı için kritik.\n\n'
          '✂️ Budama: Kış budaması temel bakım; terbiye sistemi seçimi önemli.\n\n'
          '🧪 Gübreleme: Sonbahar: Organik gübre; ilkbahar: Potasyum ağırlıklı.',
    },
    'zeytin': {
      'other_names': 'Zeytin, Olive',
      'type': 'fruit',
      'cycle': 'Perennial',
      'watering': 'Minimum',
      'sunlight': 'Full Sun',
      'soil': 'Well-drained, Rocky, Alkaline',
      'growth_rate': 'Slow',
      'care_level': 'Low',
      'maintenance': 'Low',
      'drought_tolerant': true,
      'salt_tolerant': true,
      'edible_fruit': true,
      'edible_leaf': false,
      'flowering_season': 'Mayıs-Haziran',
      'harvest_season': 'Ekim-Aralık',
      'harvest_method': 'Elle toplama, ağaç silkme',
      'pruning_month': 'Şubat, Mart',
      'origin': 'Akdeniz',
      'propagation': 'Çelikleme, Aşılama',
      'pest_susceptibility': 'Zeytin sineği, Tüylü kın, Verticillium',
      'ideal_temp_min': 5.0,
      'ideal_temp_max': 35.0,
      'ideal_ph_min': 6.0,
      'ideal_ph_max': 8.5,
      'water_need_mm_week': 5.0,
      'harvest_days': 200,
      'care_description':
          '💧 Sulama: Yaz aylarında haftada 1, kışın yok; kuraklığa çok dayanıklı.\n\n'
          '☀️ Güneş İhtiyacı: Akdeniz güneşi, tam güneş şart.\n\n'
          '✂️ Budama: Her 2-3 yılda bir gençleştirme budaması.\n\n'
          '🧪 Gübreleme: Kış: Organik gübre; çiçeklenme öncesi potasyum.',
    },
  };

  // ── Public API ────────────────────────────────────────────────────────────

  /// Get offline data by Turkish crop name (case-insensitive, partial match).
  static Map<String, dynamic>? getByName(String name) {
    final lower = name.toLowerCase().trim();
    for (final entry in _crops.entries) {
      if (lower.contains(entry.key) || entry.key.contains(lower)) {
        return Map<String, dynamic>.from(entry.value);
      }
    }
    return null;
  }

  /// All crop names available offline.
  static List<String> get allNames => _crops.keys.toList();

  /// Pre-seed PlantCacheService with all offline data (called on app start).
  /// Skips crops that are already in cache (doesn't overwrite API/Gemini data).
  static Future<void> preSeed() async {
    for (final entry in _crops.entries) {
      final existing = await PlantCacheService.get(entry.key);
      if (existing == null) {
        await PlantCacheService.save(entry.key, Map<String, dynamic>.from(entry.value));
      }
    }
  }
}
