// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANmhn4gmzkYOZrxREQrfKCkMfgUS2tf9A',
    appId: '1:615521624553:web:c365da2f309a7075156b78',
    messagingSenderId: '615521624553',
    projectId: 'agriculture-smart',
    authDomain: 'agriculture-smart.firebaseapp.com',
    storageBucket: 'agriculture-smart.firebasestorage.app',
    measurementId: 'G-SBQN4TGXY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUJsRTrfTu9RvDmFYeNDDsnYLoSyCalT4',
    appId: '1:615521624553:android:9c22757c16e0a587156b78',
    messagingSenderId: '615521624553',
    projectId: 'agriculture-smart',
    storageBucket: 'agriculture-smart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeaZrbqtXotbybR0_-9HlIkgDJDgXZeCQ',
    appId: '1:615521624553:ios:3d394690f2f35aee156b78',
    messagingSenderId: '615521624553',
    projectId: 'agriculture-smart',
    storageBucket: 'agriculture-smart.firebasestorage.app',
    iosBundleId: 'com.example.feng498',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeaZrbqtXotbybR0_-9HlIkgDJDgXZeCQ',
    appId: '1:615521624553:ios:3d394690f2f35aee156b78',
    messagingSenderId: '615521624553',
    projectId: 'agriculture-smart',
    storageBucket: 'agriculture-smart.firebasestorage.app',
    iosBundleId: 'com.example.feng498',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANmhn4gmzkYOZrxREQrfKCkMfgUS2tf9A',
    appId: '1:615521624553:web:2ab175edab592a5a156b78',
    messagingSenderId: '615521624553',
    projectId: 'agriculture-smart',
    authDomain: 'agriculture-smart.firebaseapp.com',
    storageBucket: 'agriculture-smart.firebasestorage.app',
    measurementId: 'G-CP4R6VGWP1',
  );
}
